language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: Yfdfw5gKAJhBcevi9uslV17/EzpZ7ZwZq2NHmtAaWcNKgxQzGC+9zMhfcdExBB2VeVtSfablgcGheGERiAVoJIUgMypsn9Znmm2U37NgF3vp7PnE49GL3f7mu2wScRJfZzp4K28yUV2ME4imHlyvcyCRDChk+HBLv1m5OmlcL6c=
  - secure: ECa335I7NaVPHgDEo7f4sB5fk4P+TwMkYk9Z2nCyx4c8jnEAC93x3BzUcwqPKyGQmAiBBGLoWb94wnjTg6I0+MMZMhFwpayo6SqP9yN7fAtj+YqNRbYvVtJ6UjoF/GZQrsIqDn/zbfOjl3zkDNoT5KgK0FgP6uBe8ZfFWFx9qiI=
